Fix k8s namespace
rsvihladremio/dremio-diagnostic-collector pull request #63
Opened 2023-01-30 16:25 UTC by markcurtis1970

Fixes #62 - k8s namespace for cluster info

2023-01-31 12:25 UTC, rsvihladremio requested changes
Ok so this can work, but I think we should just now allow people to pass in a namespace flag --namespace and take out the old syntax of (namespace:label) while people COULD have executors and coordinators in different namespaces I don't think we have seen it once.

So I propose
* new CLI flag --namespace -n
* remove the old namespace:label syntax and just take a label name with the coordinator and executor
* increment version to 0.3.0 since this is a breaking change in the CLI

2023-01-31 14:40 UTC, rsvihladremio approved these changes

2023-01-31 14:40 UTC, rsvihladremio commented
@markcurtis1970 I went ahead and updated the PR with the changes I was thinking about, this is just easier to show you. If you approve as is, you can just merge them in. If you have better ideas then revert the commit.

2023-02-01 09:42 UTC, markcurtis1970 commented
This looks great thanks!

2023-02-01 09:42 UTC, merged